<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="e2.xsl"?>
<!DOCTYPE people [
<!ELEMENT people (person+)>
<!ELEMENT person (id, realName, nickname, gamerName, phone)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT realName (#PCDATA)>
<!ELEMENT nickname (#PCDATA)>
<!ELEMENT gamerName (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
]>
<people>
    <person>
        <id>001</id>
        <realName>นายปอง</realName>
        <nickname>ไกลตาย</nickname>
        <gamerName>สิธ</gamerName>
        <phone>0955555558</phone>
    </person>
    <person>
        <id>002</id>
        <realName>นางสาวจิต</realName>
        <nickname>อ่อน</nickname>
        <gamerName>ออม</gamerName>
        <phone>0963354782</phone>
    </person>
    <person>
        <id>003</id>
        <realName>นายปลาทอง</realName>
        <nickname>ชอบตกปลา</nickname>
        <gamerName>ปลา</gamerName>
        <phone>0954412423</phone>
    </person>
    <person>
        <id>004</id>
        <realName>นางสาวดวงจันทร์</realName>
        <nickname>วงโคจร</nickname>
        <gamerName>โคก</gamerName>
        <phone>0654125467</phone>
    </person>
    <person>
        <id>005</id>
        <realName>นายโชคดี</realName>
        <nickname>ดอกบัว</nickname>
        <gamerName>อัมบรี</gamerName>
        <phone>0854178999</phone>
    </person>
</people>
