<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="e3.xsl"?>
<!DOCTYPE products [
<!ELEMENT products (product+)>
<!ELEMENT product (id, name, price, sold, totalSold)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT sold (#PCDATA)>
<!ELEMENT totalSold (#PCDATA)>
]>
<products>
    <product>
        <id>001</id>
        <name>ยาดมโป๊ยเซียน</name>
        <price>25</price>
        <sold>991</sold>
        <totalSold>991ชิ้น</totalSold>
    </product>
    <product>
        <id>002</id>
        <name>ยาดมนวลไทย</name>
        <price>30</price>
        <sold>999</sold>
        <totalSold>999ชิ้น</totalSold>
    </product>
    <product>
        <id>003</id>
        <name>ยาดมตราวายุทอง</name>
        <price>29</price>
        <sold>899</sold>
        <totalSold>899ชิ้น</totalSold>
    </product>
    <product>
        <id>004</id>
        <name>ยาดมเซียงเพียว</name>
        <price>35</price>
        <sold>99</sold>
        <totalSold>99ชิ้น</totalSold>
    </product>
    <product>
        <id>005</id>
        <name>ยาดมมีโอรงจิต</name>
        <price>55</price>
        <sold>99</sold>
        <totalSold>99ชิ้น</totalSold>
    </product>
</products>
