<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="e4.xsl"?>
<!DOCTYPE people [
<!ELEMENT people (person+)>
<!ELEMENT person (รหัส, ชื่อ, นามสกุล, อายุ, เบอร์)>
<!ELEMENT รหัส (#PCDATA)>
<!ELEMENT ชื่อ (#PCDATA)>
<!ELEMENT นามสกุล (#PCDATA)>
<!ELEMENT อายุ (#PCDATA)>
<!ELEMENT เบอร์ (#PCDATA)>
]>
<people>
  <person>
    <รหัส>011</รหัส>
    <ชื่อ>พิภาน</ชื่อ>
    <นามสกุล>ขาลป</นามสกุล>
    <อายุ>22</อายุ>
    <เบอร์>0953840983</เบอร์>
  </person>
  <person>
    <รหัส>012</รหัส>
    <ชื่อ>ไชยา</ชื่อ>
    <นามสกุล>ไชโย</นามสกุล>
    <อายุ>30</อายุ>
    <เบอร์>0954125896</เบอร์>
  </person>
  <person>
    <รหัส>013</รหัส>
    <ชื่อ>นานา</ชื่อ>
    <นามสกุล>ไดนา</นามสกุล>
    <อายุ>28</อายุ>
    <เบอร์>0653840983</เบอร์>
  </person>
  <person>
    <รหัส>014</รหัส>
    <ชื่อ>กิมจิ</ชื่อ>
    <นามสกุล>อร่อยนะ</นามสกุล>
    <อายุ>29</อายุ>
    <เบอร์>0812456983</เบอร์>
  </person>
  <person>
    <รหัส>015</รหัส>
    <ชื่อ>ข้าวหอม</ชื่อ>
    <นามสกุล>ไว้วางเหล้า</นามสกุล>
    <อายุ>25</อายุ>
    <เบอร์>0652314520</เบอร์>
  </person>
</people>
